### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by davidovitch** [groeck/it87#101]
Based on 40bec4b5a7896d4406d2a7d095d06c0624c24aca, issue #99 and an article+comments on [Phoronix](https://www.phoronix.com/scan.php?page=news_item&px=IT87-Linux-Driver-Axing)

It doesn't mean much, and as a simple Linux user I obviously don't have the full (development) picture and context here, but I would like to say thank you for all the unpaid efforts you have put into this driver (which I use on my personal Asus X370 AMD Ryzen system). It is a real shame the manufacturers and/or other well funded stakeholders are not taking this more seriously.

With all the (potentially toxic) noise that your decision might generate I feel the urge to share my respect and gratitude for all your unpaid efforts and also to express my understanding for your decision.

**Comment by groeck** [comment]
You are welcome. The comments on Phoronix and elsewhere only confirm that I made the right decision.
