### ISSUE TITLE
1700x/1800X Temperature offset

### ISSUE THREAD

**Issue by Extarys** [groeck/it87#17]
Does the driver return the temperature of the 1700x/1800x with the +20°C temperature offset?
My guess is yes but I wanted to confirm this.

BTW thanks for the driver it works perfectly!

**Comment by groeck** [comment]
This is going to be fixed with a BIOS and/or possibly microcode update. Or at least it was with my Gigabyte AB350 Gaming 3. It is also widely mentioned on the Internet. Lets wait for a while; we can reopen if needed.
