### ISSUE TITLE
IT8692E: PWM control not working (for atleast pwm1/fan1) (GA-AX370-Gaming 5)

### ISSUE THREAD

**Issue by qantourisc** [groeck/it87#20]
Bios: F4

Could also be a bug in the BIOS. 

If there is anything I can test could help ?

**Comment by groeck** [comment]
Thanks for the report. Do you mean the IT8686E or the IT8792E ?

**Comment by qantourisc** [comment]
According to sensors "it8792-isa-0a60" does that help ?

**Comment by groeck** [comment]
Not sure where we are with this one. Closing. Please reopen with more information if problem is still seen.
