### ISSUE TITLE
`sudo make clean` fails

### ISSUE THREAD

**Issue by Enigma0** [groeck/it87#37]
:~/it87$ make clean
  CLEAN   /home/[USER]/it87/.tmp_versions
rm: cannot remove '/home/[USER]/it87/.tmp_versions/it87.mod': Permission denied
Makefile:1569: recipe for target 'clean' failed
make[1]: *** [clean] Error 1
Makefile:30: recipe for target 'clean' failed
make: *** [clean] Error 2

**Comment by groeck** [comment]
Probably because make was executed with sudo. ls -la should show the file owners. Above cmd does _not_ sghow execution with sudo, so the subject is misleading.
