### ISSUE TITLE
Cannot install the module.

### ISSUE THREAD

**Issue by Boiethios** [groeck/it87#38]
Hi, sorry if I ask a noobish question, but I cannot install the module. I typed:

```
# make
# make install
cp it87.ko /lib/modules/4.9.0-3-amd64/kernel/drivers/hwmon
depmod -a -F /boot/System.map-4.9.0-3-amd64 4.9.0-3-amd64
# modprobe it87
modprobe: ERROR: could not insert 'it87': No such device
```

My motherboard: [Tomahawk B350](https://www.msi.com/Motherboard/B350-TOMAHAWK.html#productFeature-section)
My CPU: Ryzen 1700

```
$ uname -a
Linux dv 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```

I searched around the internets but found nothing useful (I tried to force ID as mentioned in some sites). Maybe this is not the right place to get a driver for the sensors of my motherboard, but the researches I have done gave your repo as a solution.

**Comment by groeck** [comment]
Tomahawk uses nct6795d. Wrong driver. Try the nct6775 driver.

**Comment by Boiethios** [comment]
Thank you. Sorry for not finding the right driver. This is difficult to find the appropriate one with the commercial name of the motherboard.
