### ISSUE TITLE
Doesn't compile 2.6.32

### ISSUE THREAD

**Issue by mdumitrean** [groeck/it87#52]
Can we back port this driver to compile with 2.6.32?  I have Ryzen hardware and need to know temps.. 

Some of us have to use enterprise OS for stability purposes and are locked at RHEL 6/CentOS 6.

**Comment by groeck** [comment]
I don't have a system running 2.6.32. I'll be happy to accept patches.

**Comment by groeck** [comment]
Added ISSUES file describing the problem.
