### ISSUE TITLE
Instructions on setting up `it87` with dkms

### ISSUE THREAD

**Issue by adatum** [groeck/it87#95]
Would it be possible to provide instructions on setting up and updating the github version of `it87` with dkms? It would be really helpful for the uninitiated.

**Comment by groeck** [comment]
Sure. I would be more than happy to accept patches.

**Comment by adatum** [comment]
It would be easier to contribute if I didn't happen to be among the uninitiated. I can help with QA though.

**Comment by groeck** [comment]
I don't use dkms and don't know how to use it either, so we'll have to wait for someone who does.

**Comment by adatum** [comment]
I didn't realize `dkms.conf` in the repo was contributed by someone else. 

It looks like the work was already done in the Makefile in this pull request: https://github.com/groeck/it87/pull/68 

It will take a kernel update to be sure, but `make dkms` appears to work to install `it87` and set up with dkms. That info and `make dkms_clean` could be added to the main README.

Perhaps @bp0 or others could confirm if the following is recommended:
- Clone `it87` for example in `~/src`
- Run `sudo make dkms` inside the `it87` directory. This will be equivalent to `make`, `sudo make install` and setting up dkms.
- Optionally, to have `it87` load automatically at system startup, (at least for Fedora) as root do `echo it87 >> /usr/lib/modules-load.d/it87.conf`

----

One problem I noticed:

```
$ dkms status
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/it87/1.0-46-gbfbaf88/source/dkms.conf does not exist.
```
At https://github.com/groeck/it87/blob/master/Makefile#L32 `git describe --long` produces a version number prepended by a `v` (eg. `v1.0-46-gbfbaf88`), but `dkms status` expects a version number without it.

----

Lastly, I would be interested in a similar dkms-treated Makefile for the `groeck/k10temp` module. [This repo ](https://github.com/bp0/k10temp-dkms) has implemented it already, but for maintainability it would be nice to keep/duplicate it here.

**Comment by bp0** [comment]
Those instructions should work. I've been using dkms for both it87 and k10temp through several kernel updates without any problem. I'm using Xubuntu with dkms 2.3-3ubuntu9. I did not test in anything else, perhaps it is different in Fedora. We could cut off the v, if it is a causing a problem there.

**Comment by adatum** [comment]
Nevermind, the dkms error was user error. The Makefile versioning works. The problem was due to a manually installed version with dkms, which was later removed, but the directory remained and confused dkms. Removing `/var/lib/dkms/it87/1.0-46-gbfbaf88/` got rid of the error. 

```
$ dkms status
it87, v1.0-46-gbfbaf88, 4.16.15-300.fc28.x86_64, x86_64: installed (original_module exists)
nvidia, 396.24, 4.16.13-300.fc28.x86_64, x86_64: installed
nvidia, 396.24, 4.16.14-300.fc28.x86_64, x86_64: installed
nvidia, 396.24, 4.16.15-300.fc28.x86_64, x86_64: installed
```

---

@bp0 would you consider making a similar pull request for [k10temp](https://github.com/groeck/k10temp)'s Makefile with dkms?

**Comment by bp0** [comment]
I didn't notice he had k10temp. Yeah, I'll make a PR later tonight. There
needs to also be a note in the instructions about removing the old dkms
version before pulling.

**Comment by adatum** [comment]
Do you mean `make dkms_clean` must be run before `git pull`? If so, why is that?

**Comment by bp0** [comment]
`make dkms_clean` removes the current version from dkms, but after a pull, the version will have changed if there is anything worth rebuilding. Perhaps the Makefile could be improved to remove all existing versions.

**Comment by adatum** [comment]
If the Makefile can be improved, that would be great. In the meantime, a reminder in the documentation will help, as well as what to do if `git pull` is done before `make dkms_clean`.

**Comment by adatum** [comment]
I can confirm dkms and it87 worked without problems after a kernel update on Fedora 28. Thanks for the dkms and documentation efforts.
